// AUTO-GENERATED by scripts/gen-skins.js — do not edit.
// Source of truth: server/src/skins.js. Re-run `npm run gen:skins` after
// changing it. At runtime the server's catalogue (from game_start) replaces
// this, so this only backs the pre-game picker.
import type { Skin } from './protocol';

export const LOCAL_SKINS: Skin[] = [
  {
    "id": "classic",
    "group": "basics",
    "name": "Classic",
    "desc": "Plain and quick. Uses whichever colour you pick.",
    "mode": "bands",
    "pattern": null,
    "band": 1
  },
  {
    "id": "ember",
    "group": "basics",
    "name": "Ember",
    "desc": "Burns brightest at the head.",
    "mode": "gradient",
    "pattern": [
      "#FFE066",
      "#FF9E2C",
      "#FF5E1A",
      "#C81D11"
    ]
  },
  {
    "id": "bumble",
    "group": "basics",
    "name": "Bumble",
    "desc": "Small, loud, and best left alone.",
    "mode": "bands",
    "pattern": [
      "#FFC300",
      "#2B2B2B"
    ],
    "band": 3
  },
  {
    "id": "tiger",
    "group": "basics",
    "name": "Tiger",
    "desc": "Stripes earned the hard way.",
    "mode": "bands",
    "pattern": [
      "#FF8A1E",
      "#FF8A1E",
      "#2B2B2B"
    ],
    "band": 2
  },
  {
    "id": "panda",
    "group": "animals",
    "name": "Panda",
    "desc": "Looks harmless. Is not.",
    "mode": "bands",
    "pattern": [
      "#F7F7F7",
      "#F7F7F7",
      "#2B2B2B"
    ],
    "band": 3,
    "ears": {
      "shape": "round",
      "color": "#2B2B2B"
    },
    "belly": "#FFFFFF"
  },
  {
    "id": "bunny",
    "group": "animals",
    "name": "Bunny",
    "desc": "Hops between snacks.",
    "mode": "bands",
    "pattern": [
      "#FFFFFF",
      "#FFF0F3"
    ],
    "band": 4,
    "ears": {
      "shape": "long",
      "color": "#FFFFFF",
      "inner": "#FFAFC5"
    },
    "belly": "#FFFFFF"
  },
  {
    "id": "cat",
    "group": "animals",
    "name": "Alley Cat",
    "desc": "Nine lives, one arena.",
    "mode": "bands",
    "pattern": [
      "#3A3F47",
      "#2B2B2B"
    ],
    "band": 3,
    "ears": {
      "shape": "pointed",
      "color": "#3A3F47",
      "inner": "#FF9EB5"
    }
  },
  {
    "id": "cow",
    "group": "animals",
    "name": "Moo",
    "desc": "Grazes on whatever is nearest.",
    "mode": "bands",
    "pattern": [
      "#FFFFFF",
      "#FFFFFF",
      "#2B2B2B",
      "#FFFFFF",
      "#2B2B2B",
      "#FFFFFF"
    ],
    "band": 2,
    "ears": {
      "shape": "round",
      "color": "#F2AFC4"
    },
    "belly": "#FFFFFF"
  },
  {
    "id": "toxic",
    "group": "basics",
    "name": "Toxic",
    "desc": "Do not eat.",
    "mode": "bands",
    "pattern": [
      "#9BE564",
      "#1F3A17"
    ],
    "band": 2
  },
  {
    "id": "candy",
    "group": "basics",
    "name": "Candy",
    "desc": "Sweet right up until it isn’t.",
    "mode": "bands",
    "pattern": [
      "#FF6FB5",
      "#FFFFFF"
    ],
    "band": 2
  },
  {
    "id": "galaxy",
    "group": "basics",
    "name": "Galaxy",
    "desc": "Made of the good kind of space dust.",
    "mode": "gradient",
    "pattern": [
      "#F582AE",
      "#7B2CBF",
      "#3A0CA3",
      "#4CC9F0"
    ]
  },
  {
    "id": "ocean",
    "group": "basics",
    "name": "Deep",
    "desc": "Comes up from somewhere cold.",
    "mode": "gradient",
    "pattern": [
      "#7FE0F0",
      "#1982C4",
      "#0B3A66"
    ]
  },
  {
    "id": "mint",
    "group": "basics",
    "name": "Mint",
    "desc": "Cool headed.",
    "mode": "gradient",
    "pattern": [
      "#EAFFF6",
      "#41EAD4",
      "#0F8B7E"
    ]
  },
  {
    "id": "lava",
    "group": "basics",
    "name": "Lava",
    "desc": "Cooling on the outside only.",
    "mode": "bands",
    "pattern": [
      "#FF4800",
      "#2B2B2B",
      "#FF7B00",
      "#2B2B2B"
    ],
    "band": 2
  },
  {
    "id": "ghost",
    "group": "basics",
    "name": "Ghost",
    "desc": "Hard to read, harder to catch.",
    "mode": "gradient",
    "pattern": [
      "#FFFFFF",
      "#D9E8F5",
      "#9FB6C9"
    ],
    "eyes": "big"
  },
  {
    "id": "rainbow",
    "group": "basics",
    "name": "Rainbow",
    "desc": "Every colour, all at once.",
    "mode": "bands",
    "pattern": [
      "#FF5E5B",
      "#FF9E2C",
      "#FFD93D",
      "#7ED321",
      "#3FA9F5",
      "#7B2CBF"
    ],
    "band": 2
  },
  {
    "id": "rex",
    "group": "beasts",
    "name": "Rex",
    "desc": "Small arms. Big opinions.",
    "mode": "bands",
    "pattern": [
      "#ABD144",
      "#86B22D"
    ],
    "band": 3,
    "scales": {},
    "belly": "#E4E897",
    "crown": {
      "shape": "snout",
      "color": "#E4E897",
      "accent": "#5F8020"
    },
    "eyes": "big"
  },
  {
    "id": "wyrm",
    "group": "beasts",
    "name": "Wyrm",
    "desc": "Crimson scales, gold on the wing.",
    "mode": "bands",
    "pattern": [
      "#C63756",
      "#B02F4B"
    ],
    "band": 3,
    "scales": {},
    "crown": {
      "shape": "horns",
      "color": "#E6D958"
    },
    "eyes": "slit"
  },
  {
    "id": "jade",
    "group": "beasts",
    "name": "Jade Dragon",
    "desc": "Older than the arena. Unimpressed by it.",
    "mode": "bands",
    "pattern": [
      "#2E9E6B",
      "#2E9E6B",
      "#1F7A50"
    ],
    "band": 3,
    "scales": {},
    "belly": "#D8E8B0",
    "crown": {
      "shape": "horns",
      "color": "#E8D98A"
    },
    "eyes": "slit"
  },
  {
    "id": "obsidian",
    "group": "beasts",
    "name": "Obsidian",
    "desc": "Scales that drink the light.",
    "mode": "gradient",
    "pattern": [
      "#3A3550",
      "#241F36",
      "#12101D"
    ],
    "scales": {
      "tint": "#4C4470"
    },
    "crown": {
      "shape": "horns",
      "color": "#6E5CA8"
    },
    "eyes": "slit"
  },
  {
    "id": "goldscale",
    "group": "beasts",
    "name": "Goldscale",
    "desc": "A hoard with a snake wrapped round it.",
    "mode": "bands",
    "pattern": [
      "#F0CB57",
      "#D9A32B"
    ],
    "band": 2,
    "scales": {
      "tint": "#F6DE9A"
    },
    "crown": {
      "shape": "horns",
      "color": "#F5E3A1"
    },
    "eyes": "slit"
  },
  {
    "id": "umbra",
    "group": "beasts",
    "name": "Umbra",
    "desc": "You hear it before you see it.",
    "mode": "gradient",
    "pattern": [
      "#474656",
      "#292835",
      "#0C0A27"
    ],
    "crown": {
      "shape": "horns",
      "color": "#8A87A8"
    },
    "eyes": "slit"
  },
  {
    "id": "gorgon",
    "group": "beasts",
    "name": "Gorgon",
    "desc": "Already half snake. This is a promotion.",
    "mode": "gradient",
    "pattern": [
      "#B67867",
      "#462748",
      "#26152B"
    ],
    "crown": {
      "shape": "frill",
      "color": "#7D3833",
      "accent": "#E8A696"
    },
    "eyes": "slit"
  },
  {
    "id": "paladin",
    "group": "warriors",
    "name": "Paladin",
    "desc": "Polished this morning. Dented by lunch.",
    "mode": "bands",
    "pattern": [
      "#FBFBFC",
      "#CBD4D5"
    ],
    "band": 3,
    "belly": "#E6EAEB",
    "crown": {
      "shape": "plume",
      "color": "#C70000",
      "accent": "#FFFD00"
    }
  },
  {
    "id": "mech",
    "group": "machines",
    "name": "Mech",
    "desc": "No eyes. Sees everything.",
    "mode": "bands",
    "pattern": [
      "#EDEBE3",
      "#FECB00"
    ],
    "band": 2,
    "crown": {
      "shape": "visor",
      "color": "#FECB00",
      "accent": "#E01B1B"
    }
  },
  {
    "id": "kris",
    "group": "warriors",
    "name": "Kris",
    "desc": "Knows exactly which of you has been good.",
    "mode": "bands",
    "pattern": [
      "#E90000",
      "#F9F9FA"
    ],
    "band": 3,
    "belly": "#F9F9FA",
    "crown": {
      "shape": "hat",
      "color": "#E90000",
      "accent": "#F9F9FA"
    }
  },
  {
    "id": "brawler",
    "group": "warriors",
    "name": "Brawler",
    "desc": "Leads with the hair.",
    "mode": "bands",
    "pattern": [
      "#477D85",
      "#3A3F5E"
    ],
    "band": 3,
    "belly": "#E9B5A3",
    "crown": {
      "shape": "plume",
      "color": "#FA6A0A",
      "accent": "#F9A31B"
    }
  },
  {
    "id": "ronin",
    "group": "warriors",
    "name": "Ronin",
    "desc": "Serves nobody. Turns beautifully.",
    "mode": "bands",
    "pattern": [
      "#242234",
      "#3A3F5E",
      "#1B2447"
    ],
    "band": 3,
    "belly": "#E9B5A3",
    "crown": {
      "shape": "topknot",
      "color": "#242234",
      "accent": "#B3B9D1"
    }
  },
  {
    "id": "shinobi",
    "group": "warriors",
    "name": "Shinobi",
    "desc": "Was behind you a moment ago.",
    "mode": "bands",
    "pattern": [
      "#283540",
      "#2B2B45",
      "#3B2027"
    ],
    "band": 3,
    "belly": "#E9B5A3",
    "crown": {
      "shape": "topknot",
      "color": "#3B2027",
      "accent": "#B9BFFB"
    }
  },
  {
    "id": "ninja",
    "group": "warriors",
    "name": "Red Mask",
    "desc": "The mask is the whole personality.",
    "mode": "bands",
    "pattern": [
      "#4A2323",
      "#753C3C"
    ],
    "band": 3,
    "belly": "#FE6767",
    "crown": {
      "shape": "plume",
      "color": "#351919",
      "accent": "#FEE6AC"
    }
  },
  {
    "id": "karasu",
    "group": "warriors",
    "name": "Karasu",
    "desc": "Crow tengu. Takes what it likes.",
    "mode": "bands",
    "pattern": [
      "#242234",
      "#14182E",
      "#7D3833"
    ],
    "band": 3,
    "crown": {
      "shape": "beak",
      "color": "#AB5130"
    }
  },
  {
    "id": "yamabushi",
    "group": "warriors",
    "name": "Yamabushi",
    "desc": "Came down off the mountain for this.",
    "mode": "bands",
    "pattern": [
      "#242234",
      "#7D3833",
      "#DFE0E8"
    ],
    "band": 3,
    "crown": {
      "shape": "beak",
      "color": "#DFE0E8",
      "accent": "#4C6885"
    }
  },
  {
    "id": "kitsune",
    "group": "animals",
    "name": "Kitsune",
    "desc": "Nine tails, and only one of them is here.",
    "mode": "bands",
    "pattern": [
      "#FFEE83",
      "#FFAE70"
    ],
    "band": 3,
    "belly": "#FFF6C9",
    "ears": {
      "shape": "pointed",
      "color": "#FFEE83",
      "inner": "#BD6A62"
    }
  },
  {
    "id": "agni",
    "group": "beasts",
    "name": "Agni",
    "desc": "A fire that decided to go somewhere.",
    "mode": "gradient",
    "pattern": [
      "#FFF6C9",
      "#FFC53D",
      "#FF8A1E",
      "#F04E06"
    ],
    "flames": {
      "core": "#FFE9A3"
    },
    "eyes": "big"
  },
  {
    "id": "aspmodeus",
    "group": "beasts",
    "name": "Aspmodeus",
    "desc": "Came up for the leaderboard.",
    "mode": "gradient",
    "pattern": [
      "#D32011",
      "#6B241B",
      "#2A1614"
    ],
    "scales": {
      "tint": "#E8503A"
    },
    "crown": {
      "shape": "horns",
      "color": "#37211E"
    },
    "eyes": "slit"
  },
  {
    "id": "sirius",
    "group": "animals",
    "name": "Sirius Bite",
    "desc": "Hunts by starlight. Yours.",
    "mode": "bands",
    "pattern": [
      "#242A6E",
      "#3D4BC4",
      "#6FCBFF"
    ],
    "band": 2,
    "scales": {
      "tint": "#A6EEFF"
    },
    "ears": {
      "shape": "pointed",
      "color": "#242A6E",
      "inner": "#6FCBFF"
    },
    "eyes": "slit"
  },
  {
    "id": "express",
    "group": "machines",
    "name": "Scaly Express",
    "desc": "Always reaches its destination, whatever the cost.",
    "mode": "bands",
    "pattern": [
      "#D62828",
      "#1D3557",
      "#F4A300",
      "#1D3557"
    ],
    "band": 2,
    "crown": {
      "shape": "visor",
      "color": "#1D3557",
      "accent": "#F7D046"
    }
  },
  {
    "id": "anky",
    "group": "beasts",
    "name": "Anky",
    "desc": "Armoured at both ends.",
    "mode": "bands",
    "pattern": [
      "#6F8B3E",
      "#5A7433"
    ],
    "band": 3,
    "scales": {
      "tint": "#DCCFA2",
      "style": "dragon"
    },
    "belly": "#CFC48F",
    "eyes": "slit"
  },
  {
    "id": "blacksmith",
    "group": "beasts",
    "name": "Black Smith",
    "desc": "Forged, cooled, and polished. Not a scale out of place.",
    "mode": "gradient",
    "pattern": [
      "#35353D",
      "#28282F",
      "#1B1B20"
    ],
    "smooth": {
      "texture": true
    },
    "eyes": "slit"
  },
  {
    "id": "elena",
    "group": "animals",
    "name": "Elena",
    "desc": "Dressed for the occasion. The occasion is eating you.",
    "mode": "gradient",
    "pattern": [
      "#E3B5AC",
      "#D6A099",
      "#C68C8A"
    ],
    "smooth": {
      "texture": true
    },
    "eyes": "gem",
    "crown": {
      "shape": "tiara",
      "color": "#D9A188",
      "accent": "#FBEFE9"
    },
    "bloom": {
      "color": "#F3C3CE",
      "center": "#E9A0B4"
    }
  },
  {
    "id": "basilisk",
    "group": "beasts",
    "name": "Basilisk",
    "desc": "Green on green on gold. Watches you back.",
    "mode": "bands",
    "pattern": [
      "#2CA04B",
      "#0F7038",
      "#63B840",
      "#2CA04B",
      "#E9B824"
    ],
    "band": 2,
    "scales": {
      "style": "serpent"
    },
    "eyes": "slit",
    "eyeColor": "#F5C518",
    "serpent": {
      "marks": "#F2C230",
      "ridge": "#7CC93F",
      "outline": "#0A4A26"
    },
    "headArt": "basilisk"
  }
] as Skin[];
