#!/usr/bin/env node
'use strict';
/**
 * Mirrors the server's skin catalogue into the app so the picker works before
 * a game starts. The server's copy always wins at runtime (it arrives in
 * `game_start` and replaces this), so drift can only ever affect the menu.
 *
 *   npm run gen:skins
 */
const fs = require('fs');
const path = require('path');

const { SKINS } = require(path.join(__dirname, '../../server/src/skins.js'));
const out = path.join(__dirname, '../src/game/skins.catalog.ts');

fs.writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-skins.js — do not edit.
// Source of truth: server/src/skins.js. Re-run \`npm run gen:skins\` after
// changing it. At runtime the server's catalogue (from game_start) replaces
// this, so this only backs the pre-game picker.
import type { Skin } from './protocol';

export const LOCAL_SKINS: Skin[] = ${JSON.stringify(SKINS, null, 2)} as Skin[];
`
);
console.log(`wrote ${path.relative(process.cwd(), out)} (${SKINS.length} skins)`);
